### ISSUE TITLE
Extend information about sprezentuj.pl

### ISSUE THREAD

**Issue by kstosiek** [dreamer/zapisy_zosia#36]
Information about the idea behind sprezentuj.pl gifts should be extended, as it lacks the most important information about the main goal.

**Comment by dreamer** [comment]
I suggest using right column in lectures site for this purpose or explaining everythin in blogpost.

**Comment by kstosiek** [comment]
I've alreade made a change. As far as I remember the eyetracker experiments on forms, the right column is as bad as paragraph text in the form. I'll go for the latter one (as it is right now) and put a separate blogpost with additional information.
