### ISSUE TITLE
User password may be changed to invalid one.

### ISSUE THREAD

**Issue by dreamer** [dreamer/zapisy_zosia#4]
For example: to contain less than 6 characters; probably it may even be blank.

**Comment by kstosiek** [comment]
It may not be blank.

**Comment by kstosiek** [comment]
Ok, it seems that there is no way to specify the password length in the Django PasswordChangeForm. We can subclass it or override clean_new_password2 ( http://code.djangoproject.com/browser/django/trunk/django/contrib/auth/forms.py ) method in runtime, but it's infeasible right now. Maybe we should relax the limitation on password during registration?

**Comment by fsieczkowski** [comment]
fixed
