### ISSUE TITLE
Lecture description block is far too wide.

### ISSUE THREAD

**Issue by dreamer** [dreamer/zapisy_zosia#8]
And hard to read because of this; should be max 75 characters; ~30 firets.

**Comment by dreamer** [comment]
bumped priority of this bug; we can consider it "low hanging fruit", this one is easy to fix

**Comment by fsieczkowski** [comment]
I think this should be consistent between lectures and the blog. Also, in both cases the text should probably be justified.

**Comment by dreamer** [comment]
```
.lecture p {
    text-indent: 1.5em;
    text-align: justify;
    text-justify: inter-word;
    text-align-last: left;
    max-width: 45em;
}

strong.lecture_author + p { text-indent: 0; }
```

fixed (according to polish typographic conventions ;) )
